version: '3'

services:
  server:
    image: server-fastify
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - logs:/dockerdir/logs
      - ./src:/dockerdir/src

  postgres:
    build: ./database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db:${PGDATA}

volumes:
  logs:
  db: