version: '3'

services:
  server:
    build: .
    ports:
      - ${PORT}:${PORT}
    restart: always 
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
    volumes:
      - logs:/dockerdir/logs
      - ./src:/dockerdir/src
    networks:
      - my-custom-net

  postgres:
    build: ./database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    volumes:
      - db:${PGDATA}
    networks:
      - my-custom-net 

networks:
  my-custom-net:
    driver: bridge

volumes:
  logs:
  db: